### ISSUE TITLE
If it is just a declaration without code, maybe you should not upload it to GitHub.

### ISSUE THREAD

**Issue by cynic-1** [zksync/credo#1]
You are supposed to deal with code when it comes to GitHub. I can get your point since it is related to collaboration and discussion, but maybe you can do it in some forum.

**Comment by nerovic** [comment]
Maybe it is here for a reason. Time will tell...

**Comment by gluk64** [comment]
Github is used to make contribution PRs (and discussions about them) easier.

**Comment by dirus4874** [comment]
Github is used to make contribution PRs (and discussions about them) easier.

**Comment by khoavtvn1991** [comment]
Agreed. GitHub is used for coding and issues, not a forum for a public discussion.

**Comment by Virex48** [comment]
It will come

**Comment by mlilvic** [comment]
It’s a start of something. Give it time

**Comment by Hazemabuzer** [comment]
Agree

**Comment by joey8447665** [comment]
He said maybe and I think github is good.

**Comment by ananaer** [comment]
Time is answer

**Comment by bxpana** [comment]
@cynic-1 thanks for your feedback and we'll work on providing more details of how the community can get involved with the ZK Credo. 

When we talk about community we are talking about all the stakeholders in zkSync. That includes, users, devs, projects, etc. 

We don't have a voting process right now, but that's something we can think about for the future. Thanks again and we'll let everyone know when there are updates.
