### ISSUE TITLE
Paymaster fees

### ISSUE THREAD

**Issue by mrkay100** [zksync/credo#100]
It appears that some platforms might be taking advantage of the whole paymaster transactions. I paid over 1 dollar just to approve a token. An amount that I would use to swap tokens severally without Paymaster. 

This is not what Zksync stands for and I would be happy if this is looked into ASAP. Let the zksync team try to speak to the different ecosystem projects that integrates paymaster feature.

**Comment by RexKizzy** [comment]
This is really outrageous
