### ISSUE TITLE
French Traduction difficulties to resolve before pull request

### ISSUE THREAD

**Issue by MarcVlad** [zksync/credo#14]
Hello / Salut,

I have translated the credo into French but had an issue translating the terms: " Internet of Value", "Onward" & "Magic Moon Math".
 
French speakers, I'd love to hear your translation ideas for the above terms and don't hesitate to update my translation (or I will do it from our discussion).

[Zk credo-FR.odt](https://github.com/zksync/credo/files/11887553/Zk.credo-FR.odt)

For OSS, privacy, freedom and digital self-ownership!

M.V.

**Comment by MarcVlad** [comment]
**ZK CREDO

Liberté → Progrès → Prospérité**

L'histoire nous a enseigné que la technologie peut être un puissant vecteur de liberté individuelle, de créativité et d'innovation, ouvrant la voie au progrès et à la prospérité.

Dès les premières civilisations, les librairies, les archives et les registres ont permis de suivre l'évolution des échanges, donnant aux individus et aux communautés les moyens de gérer leurs finances et de coopérer plus efficacement. L'imprimerie a quant à elle démocratisé l'accès au savoir en rendant l'information plus accessible, stimulant ainsi la pensée critique et le progrès scientifique.

La révolution industrielle, portée par les avancées technologiques de la mécanisation et de la machine à vapeur, a engendré une prospérité économique et sociale sans précédent.

Au XXe siècle, l'essor de la cryptographie et d'Internet a transformé la communication et l'accès à l'information. Cette expansion des libertés individuelles a créé des opportunités économiques pour des milliards de personnes.

Aujourd'hui, nous sommes à l'aube d'une nouvelle ère avec les blockchains et le Web3. Comme Internet l'a fait pour l'information, le Web3 bouleverse le paysage de la propriété numérique et du commerce, offrant de nouvelles formes prometteuses d'organisation sociale, comme les "États-réseaux (Network States)" 1.

Notre voyage à travers les vagues de la révolution cryptographique se poursuit. Après les premières vagues marquées par la cryptographie à clé publique et les blockchains, nous sommes désormais confrontés à la troisième vague : la révolution ZK.

Associée au Web3, la révolution ZK est prête à redéfinir notre avenir collectif, témoignant du pouvoir de la technologie à étendre la liberté individuelle. 

**LA REVOLUTION ZK**

"ZK" est un terme difficilement définissable. À l'origine, il signifiait "Zero-Knowledge (Proofs)" ou, si vous insistez, "Zipped by Kryptographie" 2. Aujourd'hui, "ZK" incarne une idée plus large, qui se décompose en trois propriétés essentielles : l'intégrité, la confidentialité et la magie.

**L'intégrité**

_"L'intégrité consiste à faire ce qui est juste... même lorsque personne d'autre ne regarde ou ne l'apprendra."_ - Charles W. Marshall. 3.

ZK fait écho à l'éthos "Ne faites pas confiance, vérifiez" qui est au cœur des mathématiques, de l'open source et des blockchains. L'intégrité computationnelle, rendue possible à toute échelle par les preuves récursives de ZK, est la pierre angulaire de cet élément.

**Confidentialité**

_"La protection de la vie privée est essentielle pour une société libre à l'ère électronique."_ - Eric Hughes 4.

Dans l'univers des blockchains, la confidentialité pose des défis auxquels la ZK répond de manière unique. La confidentialité ne doit pas être un cadeau que l'on nous fait ; c'est un droit fondamental que nous devons affirmer et défendre ensemble.

**Magie**

_"Toute technologie suffisamment avancée est indiscernable de la magie."_ - Arthur C. Clarke 5.

ZK, surnommé "Magic Moon Math", est une merveille technologique. Elle simplifie l'alambiqué, elle transforme des opérations compliquées en quelques clics. Elle rend possible l'intégation de ystèmes dont les composantes se synchronisent de manière fluide. Surtout, elle tisse ces merveilles en honorant la vie privée et la souveraineté de l'utilisateur. 

**Les principes ZK**

Nous croyons que pour devenir les fondations de l'économie libre de l'Internet, les réseaux décentralisés doivent adhérer aux principes suivants :

**L'absence de confiance**
Les utilisateurs doivent être en mesure de vérifier l'intégrité des transactions et l'état du réseau de manière indépendante, sans dépendre d'autrui.

**Sécurité**
Une attaque contre un utilisateur individuel doit être aussi difficile et coûteuse qu'une attaque contre l'ensemble du réseau, même pour les acteurs mondiaux les plus puissants.

**Fiabilité**
Le réseau doit remplir ses fonctions avec consistance et sans défaillance.

**Résistance à la censure**
Les utilisateurs doivent pouvoir effectuer des transactions sur le réseau sans avoir besoin de l'autorisation de qui que ce soit.

**Protection de la vie privée**
Les utilisateurs doivent pouvoir protéger leur identité et les détails de leurs transactions. Les informations sensibles ne sont pas partagées avec d'autres membres du réseau sans le consentement des utilisateurs.

**Hyperscalabilité**
Le réseau doit avoir la capacité de croître sans limite tout en préservant toutes ses autres propriétés essentielles.

**Accessibilité**
Les applications et les services du réseau doivent être aussi abordables, faciles à utiliser et sûrs que leurs homologues centralisés.

**Souveraineté**
Tout groupe d'utilisateurs, même minoritaire, doit avoir le droit de sortir du réseau, c'est-à-dire de le quitter en emportant ses actifs à un coût minimal.

À l'heure actuelle, Ethereum est la blockchain qui se rapproche le plus d'accomplir la vision d'un réseau blockchain formant la colonne vertébrale l'"Internet of Value". Il s'agit d'un réseau sécurisé, fiable, résistant à la censure et souverain. Cependant, il ne remplit pas les autres conditions préalables : protection de la vie privée, l'hyperscalabilité et l'accessibilité.

Grâce à ZK, le Web3 sur Ethereum peut devenir un bastion de la vie privée et atteindre une scalabilité illimitée tout en maintenant son intégrité. Dans cet état transformatif, il sera un sanctuaire accessible et abordable pour l'auto-propriété numérique. 

En s'alignant sur la vision de la ZK, il donnera le pouvoir aux individus à l'échelle mondiale, indépendamment de leur localisation. En libérant ces capacités, une nouvelle vague de liberté, de progrès et de prospérité impactera la vie des gens dans le monde entier.

**L'Action Collective**

Les principes ZK assurent la mise en place d'un réseau où il n'est pas nécessaire de faire confiance à qui que ce soit pour sécuriser les actifs et la souveraineté des utilisateurs. Même si Voldemort avait accès à nos serveurs, il ne pourrait pas porter atteinte à la propriété des utilisateurs.

Cependant, la technologie évolue et les blockchains aussi. Les principes ZK ne peuvent pas être entièrement protégés uniquement par la technologie. Pour garantir une protection durable, la communauté doit embrasser le concept élusif de décentralisation.

Si un réseau remplit tous les principes ZK mais que sa gouvernance tombe entre les mains de quelques privilégiés, il est voué à l'échec. Ces quelques privilégiés modifieront les règles à des fins personnelles, ce qui aura pour effet d'éroder la valeur du réseau. L'histoire de l'Internet est un exemple de mise en garde. Sa création promettait la décentralisation, mais au fil du temps, les données et le trafic des utilisateurs sont tombés sous le contrôle de quelques géants de la technologie, qui ont façonné le paysage numérique à leur avantage.

Pour éviter ce destin, nous pensons que la communauté ZK doit être farouchement souveraine et considérer son droit d'optionalité comme une obligation morale. Lorsque le réseau s'écarte de ses principes, la communauté doit s'unir et défendre ces valeurs en migrant vers un nouveau réseau.

L'identification d'une telle érosion des valeurs n'est pas triviale : l'oppression est souvent subtile et érode lentement la liberté. Les oppresseurs peuvent également punir publiquement les dissidents afin de susciter la peur et promouvoir l'inaction collective.

Face à ces tactiques, une réponse collective est essentielle. La communauté doit protéger les minorités et célébrer ceux qui défient l'oppression. Il est essentiel d'ancrer profondément cet engagement collectif dans l'ethos communautaire afin de préserver la liberté sur l'"Internet of Value".

La réalisation des principes ZK nécessite du temps et de la persévérance. Une approche stable et pragmatique de la décentralisation est nécessaire. Si des compromis à court terme peuvent être faits, la vision inébranlable à long terme demeure : faire progresser la liberté individuelle pour tous.

Restons déterminés à être les champions l'auto-propriété numérique

En Avant!

**Comment by cynic-1** [comment]
Seems the team is busy with ZK Stack and don't have time to deal with credo.
I submit a PR 2 days ago and don't get any reply from the team.

**Comment by XofEE** [comment]
Beau boulot, c'est une excellente traduction. Ce n'est pas facile de trouver une traduction pour "Internet of Value" en français, car il n'y a pas de consensus clair. Peut-être que "Économie Numérique" ou "Internet des Transactions" pourraient convenir

Good job, it's an excellent translation. It's not easy to find a translation for "Internet of Value" in French because there is no clear consensus. Perhaps "Économie Numérique" or "Internet des Transactions" could be suitable

**Comment by MarcVlad** [comment]
Je pensais à "l'économie de l'internet" ou "économie numérique".

**Comment by arose0** [comment]
Hey @MarcVlad - thanks for working on the translation! Do you want to open a pull request for review & so that it can be merged?

**Comment by bxpana** [comment]
@cynic-1 we appreciate your submission and will be going over them soon. Thanks for being apart of this!
