### ISSUE TITLE
Airdrop discussion

### ISSUE THREAD

**Issue by sioodmy** [zksync/credo#2]
Your amazing whitepaper didn't mention plans for future airdrop. Is such a thing even planned?
I understand if you, as a team, are not comfortable sharing such an information right now, feel free to clsoe the issue if you feel like it.

My main question is how are you going to distinguish real zkSync users from bot farmers? In my opinion gitcoin passport would be fair, but it should be announced earlier, cuz it's not THE STANDARD (yet)

**Comment by khoavtvn1991** [comment]
Gitcoin passport requires a social account like twitter, facebook, or google... Otherwise, you can not get a high score. 
It is not fit with the zkSync vision about privacy. Additionally, this is L2 world. So the more you contribute to the network, the bigger prize that you will get.
I think the criteria distinguishing real zkSync users from bot farmers are network volume, number of tx, number of active days, and number of interactions with Dapp. That's all.

**Comment by sioodmy** [comment]
any transaction volume/value checks would be unfair to me
for example lets have a look at my wallet `0x2fa1E5e90C011d08BbA1f6dbdc317FD293311c0D`
![image](https://github.com/zksync/credo/assets/81568712/9f6e3fa5-3f1b-4e6c-8ae6-d6f523941d14)
as you can see on [debank](https://debank.com/profile/0x2fa1e5e90c011d08bba1f6dbdc317fd293311c0d) I am a pretty active user of other evm blockchains, but it does not guarantee that I'm 100% real user.

Even if we considering gitcoin passport wouldn't be as strong evidence 
![image](https://github.com/zksync/credo/assets/81568712/d4fbb77a-d398-4b73-82df-e58b5f91a7c2)
most of the tasks listed can be easily completed without KYC

We could look at first transaction of specific wallet or check connections to eliminate sybils, but this could create many false-positives like for example me sending funds from `0xCef744F9DA90AE4799BC2FF7DD5E3810d1fF54D8` (hot wallet) to my ledger once it arrived. Another example is buying crypto for family and friends without CEX accs or exchanging test tokens on twitter due to poorly designed faucets (like linea) 

Another thing to talk about is if you guys consider so called "airdrop hunting" as a bad thing. Like for example I interact with zksync era projects on daily basis on my main and only active wallet. Yeah of course sometimes I swap more times than I actually need on syncswap (dont blame me im raising some money for a gift to my gf). I know that it creates fake traffic and more load than its necessary, so I'm asking if you consider it as a "stress test" for the network.

I'm sure that zkSync team has some solution to this problem and I would love to read about your standpoint

**Comment by Hazemabuzer** [comment]
I think the kyc by gitcoin and galxe passport would be enough. Why the complicated kyc.

**Comment by sioodmy** [comment]
I'm not talking about KYC but im rather asking for decentralized solutions.
Of course they could have just partner up with major CEXes and force people to connect their wallets and then claim, but thats not how we want it. Crypto is already becoming more and more centralized. Just make sure to remember that decentralization does not equal full anonymity, most blockchains are already transparent, so I'm sure that solution for above mentioned problem in fact is entirely possible, even though its tricky

**Comment by joey8447665** [comment]
Gitcoin passport is not fair enough, why should I get more score through donation?

**Comment by Hazemabuzer** [comment]
> Gitcoin passport is not fair enough, why should I get more score through donation?

How many points do you have on gitcoin?

**Comment by joey8447665** [comment]
> > Gitcoin passport is not fair enough, why should I get more score through donation?
> 
> How many points do you have on gitcoin?

33 and it's uncomfortable to offer all my personal private info to the project I barely use. It sucks.

**Comment by TrashxPandaArt** [comment]
I personally am not comfortable uploading my identifying documents to things like Gitcoin and Galxe. I put a lot of stock in my relative anonymity. I am very active with a variety of DAPPS and bridges on ZK Sync and would hope to be rewarded regardless of my willingness to bust out my passport or drivers license. I think using the solution of disqualifying users who have under a minimum number of transactions will likely kill off most of the "airdrop hunters". Who are trying to get that multimillion dollar pipe dream of a payday from an airdrop. I also think it would be a shame to disqualify relatively new community members. It seems like maybe a few months of faithful activity would be sufficient? With something like 50 transactions? I have no idea if any of your guys are developing on chain or what... but I like it that way. Anonymity. - TrashxPanda

**Comment by asgharsata1** [comment]
> من شخصاً از آپلود اسناد شناسایی خود در مواردی مانند Gitcoin و Galxe راحت نیستم. من سهام زیادی را در ناشناس بودن نسبی خود قرار دادم. من با انواع DAPPS و پل‌ها در ZK Sync بسیار فعال هستم و امیدوارم بدون توجه به تمایلم برای رد کردن گذرنامه یا گواهینامه رانندگی، پاداش دریافت کنم. من فکر می کنم استفاده از راه حل رد صلاحیت کاربرانی که کمتر از حداقل تعداد تراکنش دارند، احتمالا اکثر "شکارچیان دراپ" را از بین می برد. کسانی که سعی می کنند آن لوله چند میلیون دلاری را از یک ایردراپ به دست آورند، رویای یک روز حقوق را دارند. من همچنین فکر می کنم شرم آور است که اعضای نسبتاً جدید جامعه را رد صلاحیت کنیم. به نظر می رسد شاید چند ماه فعالیت وفادارانه کافی باشد؟ با چیزی حدود 50 تراکنش؟ من نمی دانم که آیا هیچ یک از بچه های شما در حال پیشرفت در زنجیره هستند یا چه ... اما من آن را دوست دارم. ناشناس بودن.

That's right. My opinion is the same.

**Comment by sioodmy** [comment]
@gluk64 Would you mind sharing your thoughts?

**Comment by sioodmy** [comment]
![image](https://github.com/zksync/credo/assets/81568712/bfce828c-39eb-4938-b985-a8cbdcc1fc2a)
77% of zk wallets have never used DEX in their entire lifespan 
thats around 1,3M potential sybil wallets

I wonder how many of them have at least 10 points on gitcoin passport :eyes:

**Comment by Hazemabuzer** [comment]
> ![image](https://user-images.githubusercontent.com/81568712/248561587-bfce828c-39eb-4938-b985-a8cbdcc1fc2a.png) 77% of zk wallets have never used DEX in their entire lifespan thats around 1,3M potential sybil wallets
> 
> I wonder how many of them have at least 10 points on gitcoin passport 👀

Well .. i think most of them didn't know how to use dex. They just doing some bridge between l1 &l2

**Comment by sioodmy** [comment]
I've also thought about this idea of giving special nfts (or just a mint whitelist) to hand-picked community members and developers (I'm not talking about big teams like syncswap or mute).

let's take a look at [this guy](https://github.com/ByFishh) 
he created an amazing tool called [zkFlow](https://byfishh.github.io/zk-flow/?address=0x2fa1E5e90C011d08BbA1f6dbdc317FD293311c0D) to track zksync activity. 

he has made his wallet address available, so we can take a look at the portfolio 
![image](https://github.com/zksync/credo/assets/81568712/2a2bec04-8d37-4ab6-add2-8338879c8fae)
nothing impressive, right?
but should he get a bigger (potential) airdrop than the guy who bridged 10ETH and spammed with mute transactions?
ABSOLUTELY YES

on the blockchain it may seem that the latter is more dedicated, but is that the case? If the future token is going to be used for management, we need to make sure we dump the tokens to the right people with actual knowledge, not just people who want to make money from it (by selling them to one friggin' entity). 

I'm sorry, but this is critical to keeping zkSync decentralized and strong. Airdropping tokens to everyone or organizing an 
ICO could have disastrous consequences for the community, as well as for the entire project  

I have a lot of free time right now, so maybe I could help with selecting above-mentioned addresses 

email: hello[at]sioodmy.dev
pgp key: https://sioodmy.dev/public.key
pgp fingerprint: D656 43B1 72BA 33B9 74A5  9CC4 056C FD15 A9F9 9B0E

**Comment by khoavtvn1991** [comment]
Sorry but "the guy who bridged 10ETH and spammed with mute transactions" is really contributing to the project. If you know how much he pays for the price slippage and fee, you won't say that. But we must remove all wrap/unwrap ETH transactions, many airdrop farmers do this way to avoid losing money by price slippage and fee

**Comment by sioodmy** [comment]
> Sorry but "the guy who bridged 10ETH and spammed with mute transactions" is really contributing to the project. If you know how much he pays for the price slippage and fee, you won't say that. But we must remove all wrap/unwrap ETH transactions, many airdrop farmers do this way to avoid losing money by price slippage and fee

I disagree
why would we reward people just for being rich?

Mindlessly spending money on project should not be prioritized over actively contributing to the zkSync ecosystem. Expanding and embracing the ecosystem actually helps our community and keeps zksync thriving and alive. 

I'm absolutely sure that 99.99% of "airdrop hunter/crypto bros" never heard of [zero knowledge proof](https://en.wikipedia.org/wiki/Zero-knowledge_proof). 
(If I had to guess, probably there are like 5000 people at most that actually know what zero knowledge proof actually is )
Do they really deserve to be able to vote? Do they know anything about zkSync project?

Let's be real, most of them wants to claim free funni internet moni and then dump it as soon as they can. Also vesting is not a real solution to this problem, as people will be afraid to build and use zksync because they will think they are sitting on a ticking bomb that will explode when the tokens are unlocked.

**Comment by arnolwijaya77** [comment]
> I think the kyc by gitcoin and galxe passport would be enough. Why the complicated kyc. 
I think so

**Comment by arnolwijaya77** [comment]
> I think the kyc by gitcoin and galxe passport would be enough. Why the complicated kyc.

**Comment by khoavtvn1991** [comment]
Why do we need KYC in this case? zkSync focus on privacy, so I don't think they need every user with verified KYC to get the reward. They should focus on on-chain activities. That's all

**Comment by khoavtvn1991** [comment]
> > Sorry but "the guy who bridged 10ETH and spammed with mute transactions" is really contributing to the project. If you know how much he pays for the price slippage and fee, you won't say that. But we must remove all wrap/unwrap ETH transactions, many airdrop farmers do this way to avoid losing money by price slippage and fee
> 
> I disagree why would we reward people just for being rich?
> 
> Mindlessly spending money on project should not be prioritized over actively contributing to the zkSync ecosystem. Expanding and embracing the ecosystem actually helps our community and keeps zksync thriving and alive.
> 
> I'm absolutely sure that 99.99% of "airdrop hunter/crypto bros" never heard of [zero knowledge proof](https://en.wikipedia.org/wiki/Zero-knowledge_proof). (If I had to guess, probably there are like 5000 people at most that actually know what zero knowledge proof actually is ) Do they really deserve to be able to vote? Do they know anything about zkSync project?
> 
> Let's be real, most of them wants to claim free funni internet moni and then dump it as soon as they can. Also vesting is not a real solution to this problem, as people will be afraid to build and use zksync because they will think they are sitting on a ticking bomb that will explode when the tokens are unlocked.

I don't think people need to know zk proof to involve in zkSync project. It is based on mathematics and hard to understand if you are not good at Math. They just need to know basic concept of zk proof and how zkSync team used it.
 But I agree with you, most of zkSync wallet now is airdrop hunter. And almost on-chain activities now are farming. So the on-chain volume, the distinct smart contract interaction, and the week/month active may be the most criteria to recognize real user and bot/spam user.

**Comment by sioodmy** [comment]
> > > Sorry but "the guy who bridged 10ETH and spammed with mute transactions" is really contributing to the project. If you know how much he pays for the price slippage and fee, you won't say that. But we must remove all wrap/unwrap ETH transactions, many airdrop farmers do this way to avoid losing money by price slippage and fee
> > 
> > 
> > I disagree why would we reward people just for being rich?
> > Mindlessly spending money on project should not be prioritized over actively contributing to the zkSync ecosystem. Expanding and embracing the ecosystem actually helps our community and keeps zksync thriving and alive.
> > I'm absolutely sure that 99.99% of "airdrop hunter/crypto bros" never heard of [zero knowledge proof](https://en.wikipedia.org/wiki/Zero-knowledge_proof). (If I had to guess, probably there are like 5000 people at most that actually know what zero knowledge proof actually is ) Do they really deserve to be able to vote? Do they know anything about zkSync project?
> > Let's be real, most of them wants to claim free funni internet moni and then dump it as soon as they can. Also vesting is not a real solution to this problem, as people will be afraid to build and use zksync because they will think they are sitting on a ticking bomb that will explode when the tokens are unlocked.
> 
> I don't think people need to know zk proof to involve in zkSync project. It is based on mathematics and hard to understand if you are not good at Math. They just need to know basic concept of zk proof and how zkSync team used it. But I agree with you, most of zkSync wallet now is airdrop hunter. And almost on-chain activities now are farming. So the on-chain volume, the distinct smart contract interaction, and the week/month active may be the most criteria to recognize real user and bot/spam user.

I agree, real zkSync users should receive the *potential* airdrop (potential because we are only speculating), however people who build around the zkSync ecosystem deserve more love and no, I'm not talking about huge projects (like any dapp listed on https://ecosystem.zksync.io/), but small devs experimenting and gaining experience while building on zksync. 

I think it would be fair if zkSync team decided to make some kind of "Education Grant" or something like that, opportunities are endless. It could be linear 5 year vesting to keep them on chain. It could be on top of the airdrop or devs would have to chose whether they want "quick cash" or if they actually believe in the project, 5 year vesting with more tokens. But that's up to the zkSync developers to decide. I'm sure they're reading this (I wish you all a pleasant rest of the day, keep going) , but it's wise for them to remain silent because they know that when they respond, the crypto bros will already be configuring their lambos

**Comment by voyage11** [comment]
> Your amazing whitepaper didn't mention plans for future airdrop. Is such a thing even planned? I understand if you, as a team, are not comfortable sharing such an information right now, feel free to clsoe the issue if you feel like it.
> 
> My main question is how are you going to distinguish real zkSync users from bot farmers? In my opinion gitcoin passport would be fair, but it should be announced earlier, cuz it's not THE STANDARD (yet)

Any KYC or identity verification is soooo Web 2.0. We are now in a new Era - Web 3.0

If KYC is being enforced, 3 of the ZK Principles might be violated:-
> **Trustlessness**. Users must be able to verify the integrity of transactions and the network state independently, without relying on others.
> 
> **Censorship-Resistance**. Users must have the ability to transact on the network without needing permission from anyone.
> 
> **Privacy**. Users must be able to protect their identities and transaction details. Sensitive information is not shared with others in the network without the consent of users.

Bot farmers/Sybil attackers could be detected using other methods such as algorithms/AI.

**Comment by bmosavi** [comment]
برای افزایش امتیاز گیت کوین سعی کنید از لینک https://getpass.civic.com استفاده کنید و بهتون حداقل ۶ امتیاز میده

**Comment by asgharsata1** [comment]
ممنون

**Comment by arnolwijaya77** [comment]
👍

**Comment by bxpana** [comment]
Thanks for everyone's feedback here, but we're going to close this comment since this thread is not related to the ZK Credo.

**Comment by asgharsata1** [comment]
👍
