### ISSUE TITLE
Feedback regarding governance

### ISSUE THREAD

**Issue by 0xiliyan** [zksync/credo#3]
ZK principles should be safeguarded properly via verified decentralized nodes (single users). In terms of governance this could work like that - one verified human (not bot) has private zk proof of humanity and has the ability to vote with power of one, this eliminates bots / bad actors and ensures only trustworthy participants that can influence governance via sufficient decentralization.

This is contrary to networks where whales can manipulate by holding lots of tokens (e.g. A16z voting on Uniswap) or bot accounts can influence voting as well. By leveraging ZK technology users can privately authenticate themselves and participate in network governance and decentralization.

If there is an attack vector on a single user then only single node (vote) will be affected.

Based on your draft I believe ZK Credo could be an advanced Credibility protocol based on zk-proofs that can be embraced by multiple networks and not only Ethereum L1/L2.

I hope my feedback has been useful @gluk64 

Regards,
0xiliyan

**Comment by 0xsisyfos** [comment]
Thank you @0xiliyan for your suggestion.

I agree that having a 'proof-of-humanity' protocol would be beneficial for the governance of projects. It offers potentially an alternative to wealth-based voting system. 

Would you have suggestions of designs for such proof-of-humanity based on ZK Tech? Did you come across projects that have working products?

**Comment by fnine30** [comment]
Why zkrollups fees higher than optimistic rollups?

**Comment by three7b5** [comment]
Snapshot Votings
