### ISSUE TITLE
Unable to join zkSync community in Discord.

### ISSUE THREAD

**Issue by Thang1usd** [zksync/credo#44]
I joined the zkSync group in Discord a long time ago and didn't violate any community standards, but somehow I'm now kicked out, and can't rejoin to get a role in it. Hope for support.

**Comment by 0xsisyfos** [comment]
Hello,

Thank you for reaching out to us. 
- Make sure you have a profile picture in Discord
- Make sure you do not have words such as "admin", "airdrop", etc. in your profile name.
- If you were banned, please fill out the form and we'll review as soon as we can https://appeal.zksync.dev/.

Best regards,
