### ISSUE TITLE
about airdrop

### ISSUE THREAD

**Issue by qdtjgk** [zksync/credo#5]
I think users who use and build projects uninterruptedly for a long time should be rewarded

**Comment by sioodmy** [comment]
Duplicate of #2

**Comment by asgharsata1** [comment]
> I think users who use and build projects uninterruptedly for a long time should be rewarded

yes

**Comment by kyawsamuilove** [comment]
But don't think too much bro))

**Comment by asgharsata1** [comment]
Anyway, I hope we will all be well rewarded for our efforts
