### ISSUE TITLE
protection and restriction mechanism

### ISSUE THREAD

**Issue by haitao6** [zksync/credo#6]
As a public chain project, I think it is necessary for the public chain project itself to identify DAPP’s evil behavior through a protection and control mechanism, so as to protect users from huge financial security risks. At present, there have been many scams since various DAPPs went online. It is actually detrimental to the subsequent development of ZKSYNC. The core of decentralization is equality, not a paradise for evildoers.At present, the underlying attributes of the blockchain are based on finance, and the security of funds is especially important.

**Comment by 0xsisyfos** [comment]
Thank you @haitao6 for your message. We are working with third-party providers to provide lists of ecosystem dApps that have taken reasonable steps toward security. However, zkSync Era is a credible neutral protocol.

That being said, we are denouncing impersonators of zkSync on social media. On Discord, community members are regularly reporting scams on the scam-report channel.

zkSync Era is a permissionless protocol, anyone can build or use the network without authorization. This makes it especially critical to be alert and always do your own research (DYOR) before engaging with projects on the network. We have recently published a post on that topic: "[DYOR: Don’t Trust, Verify!](https://zksync.mirror.xyz/rWlsCglbXl-2ZrjJukDfRdgX4k7OIP6rgRea-4d_AKM)".
