### ISSUE TITLE
Zk

### ISSUE THREAD

**Issue by Opti-Mizn** [zksync/credo#70]

**Comment by thekera404** [comment]
Hello

**Comment by Iransovran** [comment]
hi

**Comment by RealizeKiramelyn** [comment]
how this?

**Comment by kamranbash** [comment]
What is this? Please post your issues guys. This is not for posting blank posts.

**Comment by sinatg1995** [comment]
good

**Comment by Iransovran** [comment]
Hello .  What is this email for?

در تاریخ چهارشنبه ۷ فوریه ۲۰۲۴،‏ ۲۰:۰۰ sinatg1995 ***@***.***>
نوشت:

**Comment by sempire72** [comment]
Hello

**Comment by cagkannn** [comment]
Are there anything to do here?

**Comment by Nightcat099** [comment]
> Are there anything to do here?

no , just say Hi

**Comment by sempire72** [comment]
Hello everyone

iOS için Outlook<https://aka.ms/o0ukef> uygulamasını edinin
________________________________
Gönderen: truong giang ***@***.***>
Gönderildi: Friday, February 16, 2024 2:45:26 PM
Kime: zksync/credo ***@***.***>
Bilgi: Burhan ***@***.***>; Comment ***@***.***>
Konu: Re: [zksync/credo] Zk (Issue #70)


Are there anything to do here?

no , just say Hi

**Comment by Armankhan566** [comment]
Hi

**Comment by vtheov** [comment]
Hello everyone, have a nice dev journey

**Comment by Harshal9900** [comment]
why everyone is spaming here ? guys use this to solve your issues not for entertainment

**Comment by Iransovran** [comment]
hi 👋 I hope today is the exact day for you, the day your dreams come true for which you worked so hard, so continue with strength... And remember that the windshield of the car is much bigger and clearer than this small one in the middle of the glass... so take your focus from the past image and move forward.
