### ISSUE TITLE
An Issue using the Paymaster Feature

### ISSUE THREAD

**Issue by Whiteobj** [zksync/credo#78]

**Comment by Whiteobj** [comment]
The paymaster feature currently has no way of adjusting the fees, especially by an amatuer. This is certainly worrying in the event of high network congestion and one can't see the actual fee he/she is paying could lead to unneccessary over payment in gas fees.

I suggest a better signer be applied in this case where a user can be able to read what he/she is signing on the network.

**Comment by Harshal9900** [comment]
why i cant use usdc as a fee in official bridge ?

**Comment by kamranbash** [comment]
> why i cant use usdc as a fee in official bridge ?

I don't think paymaster is integrated in the bridge

**Comment by Armankhan566** [comment]
Woow

**Comment by Whiteobj** [comment]
> why i cant use usdc as a fee in official bridge ?

The official bridge doesn't have the paymaster feature, gas fees are in ETH alone

**Comment by Whiteobj** [comment]
> Why matterlabs is blocked me sir please unblock me

Refer to matterlabs socials for help, I cannot help you Sir

**Comment by Armankhan566** [comment]
Please say matter lab to unblock me on github please
