### ISSUE TITLE
Extension of paymaster feature to NFTs

### ISSUE THREAD

**Issue by Raymond-kode** [zksync/credo#82]
The paymaster feature should be extended to minting and selling of NFTs too on zkSync, where people can decide to mint and sell NFTs with any token on zkSync network.

**Comment by Raymond-kode** [comment]
You can also buy using paymaster features too.

**Comment by Perdinan** [comment]
Ok

**Comment by kamranbash** [comment]
> The paymaster feature should be extended to minting and selling of NFTs too on zkSync, where people can decide to mint and sell NFTs with any token on zkSync network.

**Comment by marleymarl** [comment]
Paymasters already work this way on zkSync. You can sponsor pretty much any kind of smart contract interaction. I already built one for minting and listing NFTs over 9 months ago.

**Comment by marleymarl** [comment]
> Paymasters already work this way on zkSync. You can sponsor pretty much any kind of smart contract interaction. I already built one for minting and listing NFTs over 9 months ago.

> The paymaster feature should be extended to minting and selling of NFTs too on zkSync, where people can decide to mint and sell NFTs with any token on zkSync network.

Paymasters already work this way on zkSync. You can sponsor pretty much any kind of smart contract interaction. I already built one for minting and listing NFTs over 9 months ago.
