### ISSUE TITLE
Snapshot 

### ISSUE THREAD

**Issue by canter1** [zksync/credo#92]
Use arbitrum airdrop stimulation for zks airdrop

**Comment by Armankhan566** [comment]
Why matterlabs block me on github please unblock me on github please

**Comment by ETHGENES** [comment]
nice

**Comment by AmigoBtc** [comment]
Yeap i agree

**Comment by JuanAlfonsus** [comment]
lol

**Comment by Arindam443** [comment]
Plz Follow Arbitrum Eligibility

**Comment by lampropanagiotou** [comment]
ggg

**Comment by chj927** [comment]
Libertas Omnibus NFT = ZKS (?)

**Comment by bsklwd2** [comment]
？

**Comment by LamPhong2010** [comment]
when link check?

**Comment by Armankhan566** [comment]
Why matterlabs is blocked me on github please unblock me on github matter lab
