### ISSUE TITLE
if wallet hacked what can zksync do my suggestion

### ISSUE THREAD

**Issue by jogesh11** [zksync/credo#95]
if some wallet with loads of hard work hacked zk sync should review its active ip address and some more ways to help people,ip address can do they can send the airdrop to a user to another account after reviewing if user complain you can check if new activity happening from new ip address then they should not sent that tokens to that address and try other address to compensate

**Comment by Bendy127** [comment]
So sorry about what happened same thing happened to me my wallet got hacked and about 0.9 btc was stolen thanks to Mr John a whitehathacker who helped me recover all of it message him on telegram too t.me/Whitehathacker217
